github_key: "71e0c93b5d7a01a048de"
github_secret: "16f030018ba23193651e3ab9fabbc4585f7cb2ea"

twitter_key: "KJDBs6wGl3kPXKt1dH2Rg"
twitter_secret: "Qh43UZY0UHbbCqM7RK3dmgOC3h3VDKB8rBD60HEZ8"

facebook_key: "KJDBs6wGl3kPXKt1dH2Rg"
facebook_secret: "Qh43UZY0UHbbCqM7RK3dmgOC3h3VDKB8rBD60HEZ8"