development:
  consumer_key: CONSUMER_KEY
  consumer_secret: CONSUMER_SECRET
  oauth_token: OAUTH_TOKEN
  oauth_token_secret: OAUTH_TOKEN_SECRET
production:
  consumer_key: CONSUMER_KEY
  consumer_secret: CONSUMER_SECRET
  oauth_token: OAUTH_TOKEN
  oauth_token_secret: OAUTH_TOKEN_SECRET
